server:
  port: 8080

spring:
  application:
    name: zippyboot-app
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:postgresql://localhost:5432/zippyboot
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
    elasticsearch:
      uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: zippyboot-group
      auto-offset-reset: earliest

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: Authorization
  timeout: 2592000
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

zippyboot:
  infra:
    mybatis:
      map-underscore-to-camel-case: true
      print-sql: true
    satoken:
      login-type: login
      token-prefix: Bearer
    storage:
      # LOCAL | S3
      type: LOCAL
      public-base-url: ""
      date-path-pattern: yyyy/MM/dd
      # UUID | ORIGINAL
      filename-strategy: UUID
      # APPEND_SUFFIX | FAIL | OVERWRITE
      conflict-strategy: APPEND_SUFFIX
      local:
        root-path: ./uploads
        access-path-prefix: /uploads
      s3:
        bucket: zippyboot
        endpoint: ""
        region: us-east-1
        access-key: ""
        secret-key: ""
        domain: ""
        path-style-access: true
