server:
  port: 28080

spring:
  application:
    name: zyn-demo
  profiles:
    active: @spring.profiles.active@
  config:
    import:
      - classpath:zyn-config-common.yml
      - classpath:zyn-config-@spring.profiles.active@.yml
