# ──────────────────────────────────────────────────────────────
# 开发环境 - 本地调试
# ──────────────────────────────────────────────────────────────

spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:postgresql://localhost:5432/zyn_base
  data:
    redis:
      host: localhost
    elasticsearch:
      uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092

zyn:
  discovery:
    services:
      sys: http://localhost:28081
      netty: http://localhost:28082
  storage:
    s3:
      endpoint: http://localhost:8333
