server:
  port: 28082

spring:
  application:
    name: zyn-netty
  profiles:
    active: @spring.profiles.active@
  config:
    import:
      - classpath:zyn-config-common.yml
      - classpath:zyn-config-@spring.profiles.active@.yml

zyn:
  netty:
    tcp:
      enabled: true
      host: 0.0.0.0
      port: 29090
    udp:
      enabled: true
      host: 0.0.0.0
      port: 29091
